name: Playwright Automation

on:
  push
  # schedule:
  #   - cron: "30 11 * * *"    #runs at 11:30 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install

      - name: Run script
        run: python pipipopo.py